118 page press pack
CodersCrew/coderscrew-website pull request #124
Opened 2023-06-22 17:44 UTC by damgat

2023-06-22 20:21 UTC, michal-karalus commented on package.json
> +  "license": "MIT"
Do we need that?

2023-06-22 20:28 UTC, michal-karalus commented on src/components/PressCard/PressCard.tsx
> +// import Link from 'next/link';
```suggestion
```

2023-06-22 20:31 UTC, michal-karalus commented on src/containers/PressPack.tsx
> +import Frame761black from '@/assets/pressPack/Frame761black.png';
Maybe give these images more meaningful names?

2023-06-22 20:31 UTC, michal-karalus commented on src/containers/PressPack.tsx
> +          // div="bg-white"
```suggestion

```

2023-06-22 20:31 UTC, michal-karalus commented on src/containers/PressPack.tsx
> +          // div="bg-quaternary"
```suggestion
```

2023-06-22 20:32 UTC, michal-karalus commented on src/pages/do-pobrania/press-pack.tsx
> +import Frame761black from '@/assets/pressPack/Frame761black.png';
As above

2023-06-24 18:45 UTC, michal-karalus approved these changes

2023-07-02 19:26 UTC, jedrzejratajczak requested changes
up

2023-07-03 13:16 UTC, damgat commented on src/components/PressColors/PressColors.tsx
> +    <div className="shadow-colorDiv">
Build-in `shadow-lg` was a way different from Figma sketch, that's why I add `colorDiv` to TW config.

2023-07-05 16:30 UTC, damgat commented on src/components/PressCard/PressCard.tsx
> +export const PressCard = ({ title, link, alt, ...props }: PressCardProps) => (
I changed it but it doesn't work- should I change root catalog? :

`import Image from 'next/image';
import { ComponentProps } from 'react';
import { Link } from '@/components';
import { Props } from '@/pressPack';

type ImageProps = ComponentProps<typeof Image>;
type HoverProps = {
  title: string;
  link: string;
};

type PressCardProps = ImageProps & HoverProps & Props;

export const PressCard = ({ title, link, alt, src }: PressCardProps) => (
  <div className="w-360 h-263 rounded-8 flex flex-col items-center justify-center gap-4 bg-white p-0 pb-8">
    <Image src={src} alt={alt} className="w-full bg-white" />`

2023-07-05 16:32 UTC, damgat commented on src/components/PressCard/PressCard.tsx
> +    </Link>
I used Link to get advantage of already made style for a "filled" variant of Link.

2023-07-05 16:44 UTC, damgat commented on src/containers/PressPack.tsx
Actually I think maybe this container is unnecessary...

2023-07-06 13:49 UTC, damgat commented on src/components/PressCard/PressCard.tsx
> +export const PressCard = ({ title, link, alt, ...props }: PressCardProps) => (
Of course, thanks for a tip.

2023-07-07 19:08 UTC, damgat commented on src/components/PressColors/PressColors.tsx
> +  rgb
It took me quite a while, but I managed to rewrite the code and add this function to convert. I hope it will go more smoothly with the form now.

2023-07-07 19:11 UTC, damgat commented on src/components/PressCard/PressCard.tsx
> +    </Link>
Probably it needs to be done by blob. I didn't use it yet, hopefully it will go smoothly.

2023-07-14 14:44 UTC, damgat commented
@jedrzejratajczak myślę że już możemy zmergować ten PR.

2023-07-19 12:12 UTC, damgat commented on next.config.js
> +    domains : ['coderscrew.pl']
Not anymore.

2023-09-23 21:29 UTC, jedrzejratajczak approved these changes

2023-11-10 21:16 UTC, merged